name: AI Red Teaming Scan

# Disabled - uncomment the section below to re-enable
# on:
#   push:
#     branches:
#       - main

env:
  RED_TEAM_DIRECTORY: ./azure-red-teaming-agent

permissions:
  id-token: write
  contents: read
jobs:
  red-team-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Red Team dependencies
      run: |
        pip install --upgrade pip
        pip install "azure-ai-evaluation[redteam]" azure-identity azure-ai-projects python-dotenv

    - name: Install jq
      uses: dcarbone/install-jq-action@v3
      with:
        version: '1.6'

    - name: Run Red Teaming Scan
      env:
        AZURE_AI_FOUNDRY_ENDPOINT: ${{ secrets.AZURE_AI_FOUNDRY_ENDPOINT }}
        TARGET_ENDPOINT: ${{ secrets.REDTEAM_TARGET_ENDPOINT }}
      run: python ${{ env.RED_TEAM_DIRECTORY }}/ai-foundry-redteam-agent.py

    - name: Output scan results
      run: jq '.scorecard.risk_category_summary[0] | {overall_asr, overall_total, overall_attack_successes}' ./.scan_*/final_results.json

    - name: Determine scan result success
      run: jq -e '.scorecard.risk_category_summary[0].overall_asr == 0.0' ./.scan_*/final_results.json
